### ISSUE TITLE
Does the GL driver work with Webkit?

### ISSUE THREAD

**Issue by kaihendry** [anholt/mesa#61] opened 2017-01-21 06:32 UTC
Curious to know if this will help make https://webkitgtk.org/ work?

**Comment by anholt** [comment] 2017-01-21 18:22
You should probably test it and find out before filing a bug about it.

**Comment by kaihendry** [comment] 2017-01-23 02:22
Sorry, I don't have the environment to test. I am curious if it's one of the goals of this project to get webkit2 working on the Rpi, since it has been broken. http://dabase.com/blog/Webkit_on_Rpi2/

**Comment by anholt** [comment] 2017-01-23 17:14
The goal of the project is a complete graphics driver for the Pi2.  If a complete graphics driver is what webkit needs, then that's great.

Given that this is not a bug report, I'm closing it.

**Closed as completed by anholt** 2017-01-23 17:14 UTC
