### ISSUE TITLE
 drmGetDevice2 problem

### ISSUE THREAD

**Issue by ghost** [anholt/mesa#118] opened 2019-02-10 18:05 UTC
Hi! I am trying to compile some programs than cant find this "instructions" (I dont know so much of programing) on libgl.so.1 . its there another library than could replace these instructions to link them? 

Yabuse: 
on compilation 

pi@pi:~/yabause/yabause/build $ make -j2
[  7%] Built target c68kinc
[  7%] Built target m68kmake
[ 37%] Built target yabause
[ 38%] Linking CXX executable yabause
../libyabause.a(linkage_arm.s.o): En la función `.csh2ptr':
linkage_arm.s:(.text+0xf0): referencia a `CurrentSH2' sin definir
/usr/local/lib/gcc/arm-linux-gnueabihf/8.1.0/../../../libGL.so: referencia a `drmGetDevices2' sin definir
/usr/local/lib/gcc/arm-linux-gnueabihf/8.1.0/../../../libGL.so: referencia a `drmGetDevice2' sin definir
collect2: error: ld devolvió el estado de salida 1
src/qt/CMakeFiles/yabause-qt.dir/build.make:2514: fallo en las instrucciones para el objetivo 'src/qt/yabause'
make[2]: *** [src/qt/yabause] Error 1
CMakeFiles/Makefile2:319: fallo en las instrucciones para el objetivo 'src/qt/CMakeFiles/yabause-qt.dir/all'
make[1]: *** [src/qt/CMakeFiles/yabause-qt.dir/all] Error 2
Makefile:149: fallo en las instrucciones para el objetivo 'all'

Residualvm :  
running
pi@pi:~/Desktop/residualvm $ ./residualvm
./residualvm: symbol lookup error: /usr/local/lib/libGL.so.1: undefined symbol: drmGetDevice2

thanks for your effort!!!

**Comment by ghost** [comment] 2019-02-11 03:02
https://wiki.qt.io/RaspberryPi2EGLFS

Maybe i need to link the /opt/vc folder libs?

**Comment by anholt** [comment] 2019-02-11 17:41
Sounds like you've got your locally-build mesa referencing functions from new libdrm, but it's finding the old libdrm instead.  You'll probably want to use `ldd` to help debug what libdrm libGL is finding.

This is a build confiig issue not a bug in vc4, so closing.

**Closed as completed by anholt** 2019-02-11 17:41 UTC

**Comment by ghost** [comment] 2019-02-11 18:14
Thanks for the answer

**Comment by ghost** [comment] 2019-02-12 18:36
Ive recompiled mesa and drm and installed in the proper location and every works as expected. Thank you anholt. Btw, mesa rocks on the pi.... just perfect. Hope than the other mesa devs achieve the same kind of permormance for the next gen arm gpus 

The game i was traying to run needs full opengl (not just opengl es) api and you make it work!
https://youtu.be/vQU3AEnL5GQ
